-- Migration: Remove duplicate job records
-- Description: Remove duplicate jobs keeping only the most recent version of each job_id
-- Date: 2025-01-27

-- Step 1: Create a temporary table with the most recent record for each job_id
CREATE TEMP TABLE temp_latest_jobs AS
SELECT DISTINCT ON (job_id) 
    job_id,
    job_title,
    employer_name,
    employer_logo,
    employer_website,
    job_publisher,
    job_employment_type,
    job_employment_types,
    job_apply_link,
    job_apply_is_direct,
    apply_options,
    job_description,
    job_is_remote,
    job_posted_at,
    job_posted_at_timestamp,
    job_posted_at_datetime_utc,
    job_location,
    job_city,
    job_state,
    job_country,
    job_latitude,
    job_longitude,
    job_benefits,
    job_google_link,
    job_salary,
    job_min_salary,
    job_max_salary,
    job_salary_period,
    job_highlights,
    job_onet_soc,
    job_onet_job_zone,
    search_position_key,
    search_position_query,
    created_at,
    updated_at,
    created_by,
    updated_by
FROM source.jobs
ORDER BY job_id, created_at DESC;

-- Step 2: Delete all records from the original table
DELETE FROM source.jobs;

-- Step 3: Insert back only the most recent records
INSERT INTO source.jobs (
    job_id,
    job_title,
    employer_name,
    employer_logo,
    employer_website,
    job_publisher,
    job_employment_type,
    job_employment_types,
    job_apply_link,
    job_apply_is_direct,
    apply_options,
    job_description,
    job_is_remote,
    job_posted_at,
    job_posted_at_timestamp,
    job_posted_at_datetime_utc,
    job_location,
    job_city,
    job_state,
    job_country,
    job_latitude,
    job_longitude,
    job_benefits,
    job_google_link,
    job_salary,
    job_min_salary,
    job_max_salary,
    job_salary_period,
    job_highlights,
    job_onet_soc,
    job_onet_job_zone,
    search_position_key,
    search_position_query,
    created_at,
    updated_at,
    created_by,
    updated_by
)
SELECT 
    job_id,
    job_title,
    employer_name,
    employer_logo,
    employer_website,
    job_publisher,
    job_employment_type,
    job_employment_types,
    job_apply_link,
    job_apply_is_direct,
    apply_options,
    job_description,
    job_is_remote,
    job_posted_at,
    job_posted_at_timestamp,
    job_posted_at_datetime_utc,
    job_location,
    job_city,
    job_state,
    job_country,
    job_latitude,
    job_longitude,
    job_benefits,
    job_google_link,
    job_salary,
    job_min_salary,
    job_max_salary,
    job_salary_period,
    job_highlights,
    job_onet_soc,
    job_onet_job_zone,
    search_position_key,
    search_position_query,
    created_at,
    updated_at,
    created_by,
    updated_by
FROM temp_latest_jobs;

-- Step 4: Drop the temporary table
DROP TABLE temp_latest_jobs;